In [1]:
import numpy as np

In [2]:

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [6]:
def mae(y_predicted,y_true):
    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
        print('total_error',total_error)
        
        mae=total_error/len(y_true)
        print('mae',mae)
        return mae

In [7]:
mae(y_predicted,y_true)

total_error 0.7
mae 0.13999999999999999


0.13999999999999999

In [5]:
mae(y_predicted,y_true)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [16]:
# same function in numpy we can in cell 3 can be done in onle line
total_error=np.mean(np.abs(y_true-y_predicted))
total_error

0.5

# log function

In [19]:
np.log(0)

<ipython-input-19-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [18]:
np.log(0.000000000000000000001)

-48.35428695287496

1-1 will 0 which will become undefine

use epislon

In [20]:
epsilon=1e-15

In [25]:
y_predicted_new_max=[max(i,epsilon) for i in y_predicted]
y_predicted_new_max

[1, 1, 1e-15, 1e-15, 1]

In [26]:
y_predicted_new_min=[min(i,1-epsilon) for i in y_predicted_new_max]
y_predicted_new_min#we have done these steps because log of 0 is undefined

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [28]:
y_predicted_new_min_array=np.array(y_predicted_new_min)
y_predicted_new_min_array

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [29]:
np.log(y_predicted_new_min_array)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [30]:
np.log(y_predicted)#without conversion we got infinity values

<ipython-input-30-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [32]:
# log loss function 
-np.mean(y_true*np.log(y_predicted_new_min_array)+(1-y_true)*np.log(1-y_predicted_new_min_array))

17.2696280766844

In [35]:
# creating a funtio for log loss
def log_loss(y_true, y_predicted):
    epsilon=1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [36]:
log_loss(y_true, y_predicted)

17.2696280766844

In [37]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

## Without using numpy

In [38]:
def mse(y_true, y_predicted):#with python
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [39]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

## By using numpy

In [41]:
np.mean(np.square(y_true-y_predicted))

0.366